### ISSUE TITLE
Upgrade Shibboleth to version 4.1.5

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/shibboleth-idp4-installer#45]
The Shibboleth Project has released V4.1.5 of the Identity Provider software [1], a patch release to address some outstanding library vulnerabilities of no particular impact to the project and to update the logging libraries to pull in a somewhat hardened version released by the logback developer.

The release notes [2] provide some additional detail. Notably, a couple of more advanced features were removed from the logging library in the interest of limiting future vulnerabilities, and while we don't ship any examples of their use or expect most have used them, it is a change.

**Comment by ArthurZheng** [comment]
Thanks @trsau. We'll start upgrading to ShibV4.1.5 soon.

**Comment by trsau** [comment]
Also upgrade Jetty to version 9.4.44.v20210927

**Comment by trsau** [comment]
And upgrade the following libraries to latest stable...

**Comment by ArthurZheng** [comment]
@trsau Jetty 9.4.45 is now available  https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-distribution/9.4.45.v20220203
