### ISSUE TITLE
Unable to run the bootstrap-v4.sh file

### ISSUE THREAD

**Issue by Cadjoe** [ausaccessfed/shibboleth-idp4-installer#61]
During init, the file breaks

**Environment Specs**
- OS Rocky Linux 8.6
- RAM 4GB
- CPU 2
- DISK 32GB

1. **Error**
<img width="705" alt="Screenshot 2022-07-09 at 00 06 15" src="https://user-images.githubusercontent.com/29492191/178090988-cfbb626b-15e8-4da2-ac55-fdcf55cd7030.png">

Based on the error response I believe the issue is here:
```
function run_on_os {
    if [ -f "/etc/os-release" ]; then
        . /etc/os-release

        if [[ $OS_LIST =~ (^|[[:space:]])"$ID"($|[[:space:]]) ]]; then
           echo "Preparing to install Shibboleth IdP on $ID OS"
           echo ""
           DO_APT="false"
           DO_YUM="false"
           if [[ $YUM_LIST =~ (^|[[:space:]])"$ID"($|[[:space:]]) ]]; then
               DO_YUM="true"
           fi
           if [[ $APT_LIST =~ (^|[[:space:]])"$ID"($|[[:space:]]) ]]; then
               DO_APT="true"
           fi
        else
           echo "$ID is not currently supported by the Installer!"
           exit 1 
        fi
    else
       echo "File /etc/os-release does not exist, can not determine Operating System ID!"
       exit 1
    fi
}
```
**OR**
<img width="719" alt="shib" src="https://user-images.githubusercontent.com/29492191/178091016-b5a09c5b-32b2-4ac9-a77e-1d41f0de303f.png">

I attempted to remove that extra `echo ""`, however, I got the same error.

Thank you!

**Comment by ericeguzman** [comment]
I have this same exact issue on Rocky 8.6, Did you ever find a solution for this? @Cadjoe

**Comment by Cadjoe** [comment]
No, unfortunately, not. I'm waiting to see what happens with the next release.

**Comment by trsau** [comment]
Hi @Cadjoe and @ericeguzman,

I think the issue may be with the bootstrap-v4.ini file missing an openings or closing quote mark on one of the configuration options. For example if I remove the " from the end of line:

`ORGANISATION_NAME="The University`

then run bootstrap-v4.sh I get the same error as you are seeing. Add the " back in and all works fine.

Please check the bootstrap-v4.ini file. If you want to share the file with me directly via email, please ensure you remove and passwords from the file otherwise they may become public.

**Comment by Cadjoe** [comment]
Thanks, @trsau, for jumping to this. I certainly didn't think to check out the `.ini` file. I'll inspect it tomorrow while on the machine and get back to you.

**Comment by ericeguzman** [comment]
Thanks @trsau 
For me it was a little different. I ended up having to remove the double quotes from my LDAP_BIND_DN_PASSWORD and the script finally worked

**Comment by trsau** [comment]
Will close this issue now, but will open an new issue to investigate how to improve the processing of the .ini file.
