### ISSUE TITLE
Optionally open port 80

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/shibboleth-idp4-installer#7]
IdPs deployed behind load balancers occasionally forward their requests on port 80 rather than 433. Provide an option to allow for this configuration. Default setting is off, option to appear in Advanced settings area!

**Comment by bradleybeddoes** [comment]
I'd be strongly encouraging folks to use 443 even if it is an unwrap/rewrap job at the load balancer.

If this does go through suggest reasonable warning text be associated with it about "badness" and no "we're on a switched network" isn't reall a good enough excuse here.
