### ISSUE TITLE
Default value for idp.properties

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/shibboleth-idp4-installer#8]
The default setting for idp.properties is shibboleth.EncryptionConfiguration.GCM which causes issues for older services.

Set to shibboleth.EncryptionConfiguration.CBC to ensure older services don't fail.

**Comment by rcaught** [comment]
https://wiki.shibboleth.net/confluence/display/IDP4/GCMEncryption - Shib consortium highlights CBC as an insecure option.

**Comment by trsau** [comment]
Need to add an option for this. Set GCM to default but allow IdP admins to easily downgrade to CBC with all appropriate warning provided.
